Repository Joyseohee/igeosajo, pull requests merged in 2023-01, with the labels that each got.

#5 Feat: “추가 api 명세서 자동 생성 테스트”
  backdjango/backdjango/settings.py
  backdjango/backdjango/urls.py
  backdjango/request/serializers.py
  backdjango/request/urls.py
  backdjango/request/views.py
  backdjango/requirements.txt
Labels: 문서

#7 Joy
  backdjango/backdjango/settings.py
  backdjango/backdjango/urls.py
  backdjango/common/__init__.py
  backdjango/common/admin.py
  backdjango/common/apps.py
  backdjango/common/models.py
  backdjango/common/serializers.py
  backdjango/common/tests.py
  backdjango/common/urls.py
  backdjango/common/views.py
  backdjango/requirements.txt
Labels: 강화

#8 Joy
  backdjango/api/__init__.py
  backdjango/api/admin.py
  backdjango/api/apps.py
  backdjango/api/models.py
  backdjango/api/serializers.py
  backdjango/api/tests.py
  backdjango/api/urls.py
  backdjango/api/views.py
  backdjango/approval/admin.py
  backdjango/approval/apps.py
  backdjango/approval/models.py
  backdjango/approval/urls.py
  backdjango/approval/views.py
  backdjango/backdjango/settings.py
  backdjango/backdjango/urls.py
  backdjango/buy/__init__.py
  backdjango/buy/admin.py
  backdjango/buy/apps.py
  backdjango/buy/models.py
  backdjango/buy/tests.py
  backdjango/buy/urls.py
  backdjango/buy/views.py
  backdjango/common/__init__.py
  backdjango/common/admin.py
  backdjango/common/models.py
  backdjango/common/serializers.py
  backdjango/common/tests.py
  backdjango/common/urls.py
  backdjango/common/views.py
  backdjango/order/__init__.py
  backdjango/order/admin.py
  backdjango/order/apps.py
  backdjango/order/models.py
  backdjango/order/tests.py
  backdjango/order/urls.py
  backdjango/order/views.py
  backdjango/request/__init__.py
  backdjango/request/apps.py
  backdjango/request/models.py
  backdjango/request/serializers.py
  backdjango/request/tests.py
Labels: 수정

#9 Joy
  backdjango/api/models.py
  backdjango/api/serializers.py
  backdjango/api/urls.py
  backdjango/api/views.py
  backdjango/backdjango/settings.py
  backdjango/templates/django_filters/rest_framework/form.html
Labels: 수정

#10 Fix: “수정 프로젝트 재세팅”
  backdjango/api/models.py
  backdjango/api/serializers.py
  backdjango/api/urls.py
  backdjango/api/views.py
  backdjango/backdjango/settings.py
  backdjango/backdjango/urls.py
  backdjango/requirements.txt
  frontreact/package-lock.json
  frontreact/package.json
Labels: 수정

#16 Feat: “추가 헤더, 사이드바 추가”
  .gitignore
  backdjango/api/urls.py
  backdjango/api/views.py
  backdjango/requirements.txt
  frontreact/package-lock.json
  frontreact/package.json
  frontreact/public/index.html
  frontreact/src/App.js
  frontreact/src/App.scss
  frontreact/src/components/layout/Header.css
  frontreact/src/components/layout/Header.js
  frontreact/src/components/layout/Sidebar.css
  frontreact/src/components/layout/Sidebar.js
  frontreact/src/index.js
  frontreact/src/pages/Home.css
  frontreact/src/pages/Home.js
  frontreact/src/pages/Reqterm.js
Labels: 강화

#17 Merge pull request #17 from Joyseohee/joy
  backdjango/api/urls.py
  backdjango/api/views.py
  backdjango/backdjango/settings.py
  frontreact/src/App.js
  frontreact/src/components/layout/Header.js
  frontreact/src/components/layout/Sidebar.js
  frontreact/src/pages/Home.js
  frontreact/src/pages/Reqterm.js
Labels: 수정

#18 Feat: "수정 페이지 레이아웃 분리"
  frontreact/src/App.js
  frontreact/src/components/layout/Header.css
  frontreact/src/components/layout/Header.js
  frontreact/src/components/layout/Layouts.js
  frontreact/src/components/layout/Sidebar.css
  frontreact/src/components/layout/Sidebar.js
  frontreact/src/components/reqterm/Reqbox.js
  frontreact/src/components/reqterm/Requestmain.js
  frontreact/src/pages/Home.css
  frontreact/src/pages/Home.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/styled/Layouts.css
  frontreact/src/styled/Reqterm.css
Labels: 수정

#20 Kichan
  .gitignore
  backdjango/api/admin.py
  backdjango/api/models.py
  backdjango/api/urls.py
  backdjango/api/view_exmp.py
  backdjango/api/views.py
  backdjango/backdjango/settings.py
  frontreact/package-lock.json
  frontreact/package.json
  frontreact/public/user.png
  frontreact/src/App.js
  frontreact/src/Components/OrderProgress/DateSetting.js
  frontreact/src/Components/OrderProgress/HeaderTitle.js
  frontreact/src/Components/OrderProgress/OrderSearch.js
  frontreact/src/Components/OrderProgress/OrderView.js
  frontreact/src/Components/OrderProgress/orderTable.js
  frontreact/src/Components/OrderProgress/totalPrice.js
  frontreact/src/Components/OrderRequestList/orderReqSearch.js
  frontreact/src/Components/OrderRequestList/orderReqTable.js
  frontreact/src/components/Goal.js
  frontreact/src/components/Login.js
  frontreact/src/components/docreq/requestSendButton.js
  frontreact/src/components/docreq/requestTable.js
  frontreact/src/components/layout/Header.js
  frontreact/src/components/layout/Headerbar.js
  frontreact/src/components/layout/Layouts.js
  frontreact/src/components/layout/Sidebar.js
  frontreact/src/components/layout/modal1.js
  frontreact/src/components/reqterm/Reqbox.js
  frontreact/src/components/reqterm/Requestmain.js
  frontreact/src/components/request/ReqFilter.js
  frontreact/src/components/request/ReqList.js
  frontreact/src/components/test1.js
  frontreact/src/css/header.css
  frontreact/src/img/allicon.png
  frontreact/src/img/headerimage.png
  frontreact/src/img/icondot.png
  frontreact/src/img/iconsdeliver.png
  frontreact/src/img/iconsfinish.png
  frontreact/src/img/iconsparchase.png
  frontreact/src/index.js
  frontreact/src/pages/Cart.js
  frontreact/src/pages/ConfirmParchase.js
  frontreact/src/pages/DocReqDetail.js
  frontreact/src/pages/DocRequest.js
  frontreact/src/pages/Home.js
  frontreact/src/pages/Order.js
  frontreact/src/pages/OrderProgress.js
  frontreact/src/pages/OrderReq.js
  frontreact/src/pages/OrderRequestList.js
  frontreact/src/pages/Product.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
  frontreact/src/pages/RequestUser.js
  frontreact/src/styled/DocRequestCss.css
  frontreact/src/styled/Home.css
  frontreact/src/styled/Layouts.css
  frontreact/src/styled/LoginCss.css
  frontreact/src/styled/Reqterm.css
  frontreact/src/styled/etcCss.css
Labels: 강화

#21 Fix: "수정 대소문자 문제 해결"
  frontreact/src/components/docreq/RequestSendButton.js
  frontreact/src/components/docreq/RequestTable.js
  frontreact/src/components/layout/Modal1.js
  frontreact/src/components/orderProgress/DateSetting.js
  frontreact/src/components/orderProgress/HeaderTitle.js
  frontreact/src/components/orderProgress/OrderSearch.js
  frontreact/src/components/orderProgress/OrderTable.js
  frontreact/src/components/orderProgress/OrderView.js
  frontreact/src/components/orderProgress/TotalPrice.js
  frontreact/src/components/orderRequestList/OrderReqSearch.js
  frontreact/src/components/orderRequestList/OrderReqTable.js
  frontreact/src/pages/ConfirmParchase.js
  frontreact/src/pages/DocRequest.js
  frontreact/src/pages/OrderProgress.js
  frontreact/src/pages/OrderRequestList.js
Labels: 수정
