Repository Joyseohee/igeosajo, pull requests merged in 2023-02, with the labels that each got.

#22 Joy
  backdjango/api/views.py
  frontreact/package-lock.json
  frontreact/package.json
  frontreact/src/App.js
  frontreact/src/api/Api.js
  frontreact/src/components/Login.js
  frontreact/src/components/layout/Header.js
  frontreact/src/components/layout/Layouts.js
  frontreact/src/components/layout/Sidebar.js
  frontreact/src/components/orderProgress/OrderTable.js
  frontreact/src/components/orderRequestList/OrderReqTable.js
  frontreact/src/components/reqterm/Reqbox.js
  frontreact/src/components/request/ReqList.js
  frontreact/src/components/request/ReqListTbody.js
  frontreact/src/index.js
  frontreact/src/pages/Cart.js
  frontreact/src/pages/Home.js
  frontreact/src/pages/Main.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
  frontreact/src/pages/RequestUser.js
  frontreact/src/storage/Menu.js
  frontreact/src/styled/Layouts.css
Labels: 수정

#23 Feat: "수정 페이지명 함수명 수정"
  frontreact/src/App.js
  frontreact/src/components/Login.js
  frontreact/src/pages/Main.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
Labels: 수정

#41 Joy
  backdjango/api/apps.py
  frontreact/package-lock.json
  frontreact/package.json
  frontreact/public/userprofile.png
  frontreact/src/App.js
  frontreact/src/api/Api.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/layout/Header.js
  frontreact/src/components/layout/Layouts.js
  frontreact/src/components/layout/Modal1.js
  frontreact/src/components/reqterm/Reqbox.js
  frontreact/src/components/reqterm/ReqtermFix.js
  frontreact/src/components/reqterm/ReqtermList.js
  frontreact/src/components/reqterm/ReqtermSet.js
  frontreact/src/components/request/ConfirmModal.js
  frontreact/src/components/request/ReqFilter.js
  frontreact/src/components/request/ReqFilterBox.js
  frontreact/src/components/request/ReqList.js
  frontreact/src/components/request/ReqListTbody.js
  frontreact/src/components/request/ReqReject.js
  frontreact/src/components/request/SelectReqterm.js
  frontreact/src/pages/Main.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
  frontreact/src/storage/Menu.js
  frontreact/src/styled/Layouts.css
  frontreact/src/styled/Request.css
Labels: 강화

#42 Bomin
  frontreact/src/components/common/cartcount.js
  frontreact/src/components/product/ProductDetail.js
  frontreact/src/components/product/ProductPost.js
  frontreact/src/components/requestUser/Refuse.js
  frontreact/src/img/bookshelf.jpg
  frontreact/src/img/booksupport.jpg
  frontreact/src/img/chair.jpg
  frontreact/src/img/desk.jpg
  frontreact/src/img/drawer.jpg
  frontreact/src/img/luxurychair.jpg
  frontreact/src/img/movingdesk.jpg
  frontreact/src/img/note.png
  frontreact/src/img/pen.jpg
  frontreact/src/img/pencil.jpg
  frontreact/src/pages/Cart.js
  frontreact/src/pages/Product.js
  frontreact/src/pages/RequestUser.js
Labels: 강화

#43 Geonho
  backdjango/api/views.py
  frontreact/src/App.js
  frontreact/src/components/docreq/DocList.js
  frontreact/src/components/docreq/DocListKind.js
  frontreact/src/components/docreq/DocListSearch.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/docreq/DocPaymentDetailBtn.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/components/layout/Pagination.js
  frontreact/src/pages/DocPaymentDetail.js
  frontreact/src/pages/DocPaymentList.js
  frontreact/src/storage/Menu.js
  frontreact/src/styled/DocRequestCss.css
Labels: 강화

#44 Kichan
  backdjango/api/views.py
  frontreact/package-lock.json
  frontreact/package.json
  frontreact/src/App.js
  frontreact/src/components/orderProgress/DateSetting.js
  frontreact/src/components/orderProgress/OrderSearch.js
  frontreact/src/components/orderRequestList/OrderDataInput.js
  frontreact/src/components/orderRequestList/OrderReqSearch.js
  frontreact/src/components/orderRequestList/OrderReqTable.js
  frontreact/src/components/orderRequestList/OrderTotalReq.js
  frontreact/src/components/orderRequestList/PopupPostCode.js
  frontreact/src/css/header.css
  frontreact/src/pages/OrderParchase.js
  frontreact/src/pages/OrderProgress.js
  frontreact/src/pages/OrderRequestList.js
Labels: 강화

#47 Feat: "수정 체크박스 전체 보기에서도 가능"
  frontreact/src/App.js
  frontreact/src/api/Api.js
  frontreact/src/components/reqterm/Reqbox.js
  frontreact/src/components/reqterm/ReqtermFix.js
  frontreact/src/components/reqterm/ReqtermSet.js
  frontreact/src/components/request/ReqList.js
  frontreact/src/components/request/ReqListTbody.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
Labels: 강화

#49 Geonho
  backdjango/api/views.py
  frontreact/public/img/alert.png
  frontreact/public/img/alert2.png
  frontreact/public/img/user.png
  frontreact/src/components/Login.js
  frontreact/src/components/docreq/DocList.js
  frontreact/src/components/docreq/DocListKind.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/layout/Pagination.js
  frontreact/src/components/layout/Paging.js
  frontreact/src/components/userMainPage/CheckPeriod.js
  frontreact/src/pages/DocPaymentList.js
  frontreact/src/styled/DocRequestCss.css
  frontreact/src/styled/etcCss.css
Labels: 강화

#50 Kichan
  frontreact/src/components/SubGoal.js
  frontreact/src/components/adminMainPage/DocCountCard.js
  frontreact/src/components/adminMainPage/OrderCountCard.js
  frontreact/src/components/adminMainPage/ReqCountCard.js
  frontreact/src/components/userMainPage/CheckPeriod.js
  frontreact/src/css/header.css
  frontreact/src/img/icondocapproval.png
  frontreact/src/img/icondoccancel.png
  frontreact/src/img/icondocsubmit.png
  frontreact/src/img/iconrequest.png
  frontreact/src/pages/AdminMain.js
  frontreact/src/pages/Main.js
  frontreact/src/styled/etcCss.css
Labels: 강화

#59 Fix : "수정 피드백 반영을 위한 커밋"
  backdjango/api/views.py
  frontreact/src/components/DocApRe/DocApproBtn.js
  frontreact/src/components/DocApRe/DocApproTable.js
  frontreact/src/components/docreq/DocList.js
  frontreact/src/components/docreq/DocListKind.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/components/layout/Paging.js
  frontreact/src/components/reqterm/Reqbox.js
  frontreact/src/components/reqterm/ReqtermFix.js
  frontreact/src/components/reqterm/ReqtermSet.js
  frontreact/src/components/request/ConfirmModal.js
  frontreact/src/components/request/ReqFilterBox.js
  frontreact/src/components/request/ReqList.js
  frontreact/src/components/request/RequestButtons.js
  frontreact/src/components/request/SelectReqterm.js
  frontreact/src/pages/DocApproval.js
  frontreact/src/pages/DocApprovalDetail.js
  frontreact/src/pages/DocPaymentList.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
  frontreact/src/storage/Menu.js
  frontreact/src/styled/Reqterm.css
  frontreact/src/styled/Request.css
Labels: 수정, 강화

#63 modal 작업 및 state에 따라 UI구성 변경(20230215)
  frontreact/src/components/orderProgress/OrderView.js
  frontreact/src/components/orderProgress/TotalPrice.js
  frontreact/src/components/orderRequestList/OrderReqTable.js
  frontreact/src/components/orderRequestList/OrderTotalReq.js
  frontreact/src/pages/AdminMain.js
  frontreact/src/pages/OrderParchase.js
  frontreact/src/pages/OrderProgress.js
  frontreact/src/pages/OrderRequestList.js
Labels: 강화

#65 Bomin css 수정, 카테고리 표시
  backdjango/api/views.py
  frontreact/src/components/cart/CartDetail.js
  frontreact/src/components/cart/DeleteCart.js
  frontreact/src/components/product/ProductDetail.js
  frontreact/src/components/product/ProductFilter.js
  frontreact/src/components/product/Search.js
  frontreact/src/components/request/SelectReqterm.js
  frontreact/src/components/requestUser/ReqCancel.js
  frontreact/src/pages/Cart.js
  frontreact/src/pages/Product.js
  frontreact/src/pages/RequestUser.js
  frontreact/src/styled/Cart.css
  frontreact/src/styled/Product.css
Labels: 수정

#66 Geonho
  frontreact/src/components/DocApRe/DocApproTable.js
  frontreact/src/components/docreq/DocList.js
  frontreact/src/components/docreq/DocListKind.js
  frontreact/src/components/docreq/DocPaymentDetailBtn.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/pages/DocApproval.js
  frontreact/src/pages/DocApprovalDetail.js
  frontreact/src/pages/DocPaymentDetail.js
  frontreact/src/pages/DocPaymentList.js
  frontreact/src/styled/DocRequestCss.css
Labels: 강화

#69 수정 order에러수정 20230216
  frontreact/src/components/adminMainPage/OrderCountCard.js
  frontreact/src/components/orderProgress/DateSetting.js
  frontreact/src/components/orderProgress/HeaderTitle.js
  frontreact/src/components/orderProgress/OrderSearch.js
  frontreact/src/components/orderProgress/OrderView.js
  frontreact/src/components/orderProgress/TotalPrice.js
  frontreact/src/components/orderRequestList/OrderDataInput.js
  frontreact/src/components/orderRequestList/OrderReqDate.js
  frontreact/src/components/orderRequestList/OrderReqTable.js
  frontreact/src/components/orderRequestList/OrderTotalReq.js
  frontreact/src/components/orderRequestList/PopupPostCode.js
  frontreact/src/pages/AdminMain.js
  frontreact/src/pages/OrderParchase.js
  frontreact/src/pages/OrderProgress.js
  frontreact/src/pages/OrderRequestList.js
  frontreact/src/styled/Order.css
Labels: 강화

#70 Feat: "수정 디테일 수정 및 에러 수정"
  frontreact/src/components/DocApRe/DocApproBtn.js
  frontreact/src/components/DocApRe/DocApproTable.js
  frontreact/src/components/docreq/DocListKind.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/docreq/DocPaymentDetailBtn.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/components/layout/Modal2.js
  frontreact/src/pages/DocApproval.js
  frontreact/src/pages/DocApprovalDetail.js
  frontreact/src/pages/DocPaymentDetail.js
  frontreact/src/pages/DocPaymentList.js
  frontreact/src/pages/DocReqDetail.js
  frontreact/src/pages/DocRequest.js
  frontreact/src/styled/DocRequestCss.css
Labels: 강화

#74 Bomin ui 수정
  .gitignore
  backdjango/api/views.py
  frontreact/public/index.html
  frontreact/src/components/Login.js
  frontreact/src/components/cart/CartDetail.js
  frontreact/src/components/layout/Header.js
  frontreact/src/components/layout/Layouts.js
  frontreact/src/components/layout/Sidebar.js
  frontreact/src/components/product/PostCartModal.js
  frontreact/src/components/product/ProductDetail.js
  frontreact/src/components/reqterm/ReqtermModal.js
  frontreact/src/components/reqterm/ReqtermSet.js
  frontreact/src/components/request/ReqFilter.js
  frontreact/src/components/request/ReqList.js
  frontreact/src/components/request/SelectReqterm.js
  frontreact/src/components/requestUser/ReqCancel.js
  frontreact/src/index.css
  frontreact/src/pages/Cart.js
  frontreact/src/pages/DocPaymentList.js
  frontreact/src/pages/DocRequest.js
  frontreact/src/pages/Product.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
  frontreact/src/pages/RequestUser.js
  frontreact/src/styled/Layouts.css
  frontreact/src/styled/Product.css
  frontreact/src/styled/Request.css
Labels: 수정

#75 ui 수정 및 fetch 합치기
  frontreact/src/components/orderProgress/DateSetting.js
  frontreact/src/components/orderProgress/OrderView.js
  frontreact/src/pages/AdminMain.js
  frontreact/src/pages/Order.js
  frontreact/src/pages/OrderProgress.js
  frontreact/src/pages/OrderReq.js
  frontreact/src/pages/OrderRequestList.js
  frontreact/src/styled/Order.css
Labels: 수정

#76 병합 수정 코드 병합
  backdjango/api/views.py
  frontreact/src/App.css
  frontreact/src/components/DocApRe/DocApproTable.js
  frontreact/src/components/docreq/DocList.js
  frontreact/src/components/docreq/DocListKind.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/docreq/DocPaymentBtn.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/components/docreq/RequestSendButton.js
  frontreact/src/components/docreq/RequestTable.js
  frontreact/src/pages/DocApproval.js
  frontreact/src/pages/DocApprovalDetail.js
  frontreact/src/pages/DocPaymentDetail.js
  frontreact/src/pages/DocPaymentList.js
  frontreact/src/pages/DocReqDetail.js
  frontreact/src/pages/DocRequest.js
  frontreact/src/pages/Main.js
  frontreact/src/pages/UserMain.js
Labels: 수정

#77 Kichan
  frontreact/src/components/cart/DeleteCart.js
  frontreact/src/components/cart/PostCartToRequest.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/components/docreq/RequestTable.js
  frontreact/src/components/layout/Sidebar.js
  frontreact/src/components/orderProgress/DateSetting.js
  frontreact/src/components/orderProgress/OrderView.js
  frontreact/src/components/orderRequestList/OrderReqTable.js
  frontreact/src/components/product/PostCartModal.js
  frontreact/src/components/product/ProductDetail.js
  frontreact/src/components/product/ProductFilter.js
  frontreact/src/components/product/ProductPost.js
  frontreact/src/components/product/ProductPostEach.js
  frontreact/src/components/reqterm/ReqtermModal.js
  frontreact/src/components/reqterm/ReqtermSet.js
  frontreact/src/components/request/ReqFilterBox.js
  frontreact/src/components/request/ReqList.js
  frontreact/src/components/request/SelectReqterm.js
  frontreact/src/pages/DocPaymentDetail.js
  frontreact/src/pages/DocReqDetail.js
  frontreact/src/pages/OrderParchase.js
  frontreact/src/pages/OrderRequestList.js
  frontreact/src/pages/Product.js
  frontreact/src/pages/Reqterm.js
  frontreact/src/pages/Request.js
  frontreact/src/pages/RequestUser.js
  frontreact/src/storage/Menu.js
  frontreact/src/styled/Layouts.css
  frontreact/src/styled/Product.css
  frontreact/src/styled/Reqterm.css
  frontreact/src/styled/Request.css
Labels: 수정

#78 Feat: "수정 뷰 수정"
  backdjango/api/views.py
Labels: 수정

#79 Feat: "수정 에러 수정"
  backdjango/api/views.py
  frontreact/src/components/docreq/DocList.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/components/docreq/RequestTable.js
Labels: 수정

#81 history , view(order) 수정
  backdjango/api/views.py
  frontreact/src/pages/OrderProgress.js
Labels: 수정

#90 Geonho Merge With Main
  frontreact/public/img/alert.png
  frontreact/public/img/alert2.png
  frontreact/public/img/user.png
  frontreact/public/img/userprofile.png
  frontreact/src/components/docreq/DocListKind.js
  frontreact/src/components/layout/Paging.js
Labels: 수정

#95 수정 orderview , ordertable, orderparchase
  frontreact/src/components/orderProgress/OrderTable.js
  frontreact/src/components/orderProgress/OrderView.js
  frontreact/src/pages/OrderParchase.js
Labels: 수정

#97 오류수정 Bomin
  frontreact/src/pages/Product.js
Labels: 버그, 수정

#100 Feat: "수정 orderparchase async기능"
  frontreact/src/components/orderProgress/OrderSearch.js
  frontreact/src/pages/OrderParchase.js
  frontreact/src/pages/OrderRequestList.js
Labels: 버그

#102 Geonho merge with main
  backdjango/api/views.py
  frontreact/src/components/DocApRe/DocApproTable.js
  frontreact/src/components/docreq/DocPayment.js
  frontreact/src/components/docreq/DocPaymentTable.js
  frontreact/src/pages/DocPaymentDetail.js
  frontreact/src/styled/DocRequestCss.css
Labels: 수정

#104 Bomin 수정하기
  frontreact/src/pages/Cart.js
  frontreact/src/pages/Product.js
Labels: 수정

#105 Feat: "수정 모달 취소,확인 위치 조정"
  frontreact/src/components/orderProgress/TotalPrice.js
  frontreact/src/pages/OrderParchase.js
Labels: 수정

#106 Geonho merge with main
  frontreact/src/components/userMainPage/RequestStatus.js
  frontreact/src/pages/UserMain.js
Labels: 수정

#108 오타 수정 Bomin
  frontreact/src/pages/RequestUser.js
Labels: 버그, 수정

#109 Geonho merge with main
  backdjango/api/views.py
  frontreact/src/pages/DocReqDetail.js
Labels: 수정

#110 수정 orderview구매번호 text
  frontreact/src/components/orderProgress/OrderView.js
Labels: 수정

#112 Bomin 주석삭제,try 삭제
  backdjango/api/views.py
  frontreact/src/components/product/ProductOrder.js
  frontreact/src/pages/Cart.js
  frontreact/src/pages/Product.js
Labels: 버그
